---

version: 2
updates:
  - package-ecosystem: "cargo"  # See documentation for possible values
    directory: "/"              # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      all-deps:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
